[build]
  command = "npm run generate"
  publish = "dist"
  ignore = "git log -1 --pretty=%B | grep dependabot"

[[redirects]]
  from = "/talks"
  to = "/speaking"
  status = 301
  force = true

[[redirects]]
  from = "/talks/"
  to = "/speaking"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[images]
  remote_images = ["res.cloudinary.com", "dev-to-uploads.s3.amazonaws.com", "raw.githubusercontent.com", "theaiplatform.app"]

[build.environment]
  NODE_VERSION = "22.12.0"
